version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocritic
    - goheader
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nosprintfhostport
    - revive
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
